namespace:
  name: demo
 
image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 256Mi

service:
  port: 8111
  type: ClusterIP

configmap:
  data: "version: alpine"

replicaCount: 3
